DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS animes CASCADE;
DROP TABLE IF EXISTS user_and_anime CASCADE;

DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS users_permissions;
DROP TABLE IF EXISTS permissions;

DROP EXTENSION IF EXISTS citext;